#!/bin/sh
# postinst script
#
# This script executes before that package will be unpacked from its Debian 
# archive (".deb") file. Many 'preinst' scripts stop services for packages which
# are being upgraded until their installation or upgrade is completed

# if [ -f /etc/init.d/x10-daemon ]; then
#     /etc/init.d/x10-daemon stop
# fi

exit 0
