/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp ../controller/service/ca.cyberdine.x10.xml -p X10DbusInterface
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "X10DbusInterface.h"

/*
 * Implementation of interface class CaCyberdineX10Interface
 */

CaCyberdineX10Interface::CaCyberdineX10Interface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

CaCyberdineX10Interface::~CaCyberdineX10Interface()
{
}

