/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp ca.cyberdine.x10.xml -a X10DbusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef X10DBUSADAPTOR_H_1384832050
#define X10DBUSADAPTOR_H_1384832050

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface ca.cyberdine.x10
 */
class X10Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ca.cyberdine.x10")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"ca.cyberdine.x10\">\n"
"    <signal name=\"CommandCompleted\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"channel\"/>\n"
"      <arg direction=\"out\" type=\"u\" name=\"unit\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"command\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
"    </signal>\n"
"    <signal name=\"PropertyUpdated\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </signal>\n"
"    <signal name=\"SourceUpdated\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"address\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"value\"/>\n"
"    </signal>\n"
"    <method name=\"Send\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"channel\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"unit\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"command\"/>\n"
"    </method>\n"
"    <method name=\"Set\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"channel\"/>\n"
"      <arg direction=\"in\" type=\"u\" name=\"unit\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"AllOn\"/>\n"
"    <method name=\"AllOff\"/>\n"
"    <method name=\"GetValue\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"source\"/>\n"
"    </method>\n"
"    <method name=\"GetProperty\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"SetProperty\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"Start\"/>\n"
"    <method name=\"Stop\"/>\n"
"    <method name=\"Restart\"/>\n"
"    <method name=\"Reload\"/>\n"
"    <method name=\"Quit\"/>\n"
"  </interface>\n"
        "")
public:
    X10Adaptor(QObject *parent);
    virtual ~X10Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void AllOff();
    void AllOn();
    QString GetProperty(const QString &name);
    int GetValue(const QString &source);
    void Quit();
    void Reload();
    void Restart();
    void Send(const QString &channel, uint unit, const QString &command);
    void Set(const QString &channel, uint unit, int value);
    void SetProperty(const QString &name, const QString &value);
    void Start();
    void Stop();
Q_SIGNALS: // SIGNALS
    void CommandCompleted(const QString &channel, uint unit, const QString &command, int value);
    void PropertyUpdated(const QString &name, const QString &value);
    void SourceUpdated(const QString &address, int value);
};

#endif
