/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp ca.cyberdine.x10.xml -a X10DbusAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "X10DbusAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class X10Adaptor
 */

X10Adaptor::X10Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

X10Adaptor::~X10Adaptor()
{
    // destructor
}

void X10Adaptor::AllOff()
{
    // handle method call ca.cyberdine.x10.AllOff
    QMetaObject::invokeMethod(parent(), "AllOff");
}

void X10Adaptor::AllOn()
{
    // handle method call ca.cyberdine.x10.AllOn
    QMetaObject::invokeMethod(parent(), "AllOn");
}

QString X10Adaptor::GetProperty(const QString &name)
{
    // handle method call ca.cyberdine.x10.GetProperty
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetProperty", Q_RETURN_ARG(QString, out0), Q_ARG(QString, name));
    return out0;
}

int X10Adaptor::GetValue(const QString &source)
{
    // handle method call ca.cyberdine.x10.GetValue
    int out0;
    QMetaObject::invokeMethod(parent(), "GetValue", Q_RETURN_ARG(int, out0), Q_ARG(QString, source));
    return out0;
}

void X10Adaptor::Quit()
{
    // handle method call ca.cyberdine.x10.Quit
    QMetaObject::invokeMethod(parent(), "Quit");
}

void X10Adaptor::Reload()
{
    // handle method call ca.cyberdine.x10.Reload
    QMetaObject::invokeMethod(parent(), "Reload");
}

void X10Adaptor::Restart()
{
    // handle method call ca.cyberdine.x10.Restart
    QMetaObject::invokeMethod(parent(), "Restart");
}

void X10Adaptor::Send(const QString &channel, uint unit, const QString &command)
{
    // handle method call ca.cyberdine.x10.Send
    QMetaObject::invokeMethod(parent(), "Send", Q_ARG(QString, channel), Q_ARG(uint, unit), Q_ARG(QString, command));
}

void X10Adaptor::Set(const QString &channel, uint unit, int value)
{
    // handle method call ca.cyberdine.x10.Set
    QMetaObject::invokeMethod(parent(), "Set", Q_ARG(QString, channel), Q_ARG(uint, unit), Q_ARG(int, value));
}

void X10Adaptor::SetProperty(const QString &name, const QString &value)
{
    // handle method call ca.cyberdine.x10.SetProperty
    QMetaObject::invokeMethod(parent(), "SetProperty", Q_ARG(QString, name), Q_ARG(QString, value));
}

void X10Adaptor::Start()
{
    // handle method call ca.cyberdine.x10.Start
    QMetaObject::invokeMethod(parent(), "Start");
}

void X10Adaptor::Stop()
{
    // handle method call ca.cyberdine.x10.Stop
    QMetaObject::invokeMethod(parent(), "Stop");
}

